---
title: "p8105_hw2_mkr2158"
author: "Matariya Rattanapan"
UNI: "mkr2158"
output: github_document
date: "2025-09-30"
---

Loading tidyverse

```{r}
library(tidyverse)
library(readxl)
```

## Problem 1

Cleaning up the pols-month dataset.

```{r}
pols_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    month = recode(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April", "05" = "May", "06" = "June", "07"= "July", "08" = "August", "09" = "September", "10" = "October", "11" = "November", "12" = "December"),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )) |> 
  select(-prez_dem, -prez_gop, -day,everything())
```

Cleaning up the snp dataset.

```{r}
snp_df =
  read_csv("fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(
    month = recode(month,"1" = "January", "2" = "February", "3" = "March", "4" = "April", "5" = "May", "6" = "June", "7"= "July", "8" = "August", "9" = "September", "10" = "October", "11" = "November", "12" = "December"),
    year = case_when(
      as.numeric(year) >= 50 ~ paste0("19", year),
      as.numeric(year) < 50 ~ paste0("20", year)
    )
  ) |> 
  arrange(year, month) |> 
  select(year, month, close)
```

Cleaning up unemployment dataset.

```{r}
unemploy_df =
  read_csv("fivethirtyeight_datasets/unemployment.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_pct"
  ) |> 
  mutate(
    month = recode(month, "jan" = "January", "feb" = "February", "mar" = "March", "apr" = "April", "may" = "May", "jun" = "June", "jul" = "July", "aug" = "August", "sep" = "September", "oct" = "October", "nov" = "November", "dec" = "December"),
    year = as.character(year)
  ) |> 
  arrange(year, month) |> 
  select(year, month, unemployment_pct)
```

Merging the cleaned up pols-month, snp, and unemployment datasets. 

```{r}
merged_df =
  left_join(pols_df, snp_df, by = c("year", "month"))

finalmerge_df =
  left_join(merged_df, unemploy_df, by = c("year", "month"))
```











